In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv(r"C:\Users\Dell\Downloads\crop_production.csv")
dataset

State_Name District_Name  Crop_Year       Season  \
0       Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1       Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2       Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3       Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4       Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
...                             ...           ...        ...          ...   
246086                  West Bengal       PURULIA       2014  Summer        
246087                  West Bengal       PURULIA       2014  Summer        
246088                  West Bengal       PURULIA       2014  Whole Year    
246089                  West Bengal       PURULIA       2014  Winter        
246090                  West Bengal       PURULIA       2014  Winter        

                       Crop      Area  Production  
0                  Arecanut    1254.0      2000.0  
1       Other Kharif pulses       2.0         1.0  
2                      Rice     102.0       321.0  
3                    Banana     176.0       641.0  
4                 Cashewnut     720.0       165.0  
...                     ...       ...         ...  
246086                 Rice     306.0       801.0  
246087              Sesamum     627.0       463.0  
246088            Sugarcane     324.0     16250.0  
246089                 Rice  279151.0    597899.0  
246090              Sesamum     175.0        88.0  

[246091 rows x 7 columns]

In [3]:
dataset["State_Name"].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir ', 'Jharkhand',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana ',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
      dtype=object)

In [4]:
dataset["District_Name"].unique()

array(['NICOBARS', 'NORTH AND MIDDLE ANDAMAN', 'SOUTH ANDAMANS',
       'ANANTAPUR', 'CHITTOOR', 'EAST GODAVARI', 'GUNTUR', 'KADAPA',
       'KRISHNA', 'KURNOOL', 'PRAKASAM', 'SPSR NELLORE', 'SRIKAKULAM',
       'VISAKHAPATANAM', 'VIZIANAGARAM', 'WEST GODAVARI', 'ANJAW',
       'CHANGLANG', 'DIBANG VALLEY', 'EAST KAMENG', 'EAST SIANG',
       'KURUNG KUMEY', 'LOHIT', 'LONGDING', 'LOWER DIBANG VALLEY',
       'LOWER SUBANSIRI', 'NAMSAI', 'PAPUM PARE', 'TAWANG', 'TIRAP',
       'UPPER SIANG', 'UPPER SUBANSIRI', 'WEST KAMENG', 'WEST SIANG',
       'BAKSA', 'BARPETA', 'BONGAIGAON', 'CACHAR', 'CHIRANG', 'DARRANG',
       'DHEMAJI', 'DHUBRI', 'DIBRUGARH', 'DIMA HASAO', 'GOALPARA',
       'GOLAGHAT', 'HAILAKANDI', 'JORHAT', 'KAMRUP', 'KAMRUP METRO',
       'KARBI ANGLONG', 'KARIMGANJ', 'KOKRAJHAR', 'LAKHIMPUR', 'MARIGAON',
       'NAGAON', 'NALBARI', 'SIVASAGAR', 'SONITPUR', 'TINSUKIA',
       'UDALGURI', 'ARARIA', 'ARWAL', 'AURANGABAD', 'BANKA', 'BEGUSARAI',
       'BHAGALPUR', 'BHOJPUR', 'B

In [5]:
dataset["Crop_Year"].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010, 1997, 1998, 1999,
       2007, 2008, 2009, 2011, 2012, 2013, 2014, 2015], dtype=int64)

In [6]:
dataset["Season"].unique()

array(['Kharif     ', 'Whole Year ', 'Autumn     ', 'Rabi       ',
       'Summer     ', 'Winter     '], dtype=object)

In [7]:
dataset["Crop"].unique()

array(['Arecanut', 'Other Kharif pulses', 'Rice', 'Banana', 'Cashewnut',
       'Coconut ', 'Dry ginger', 'Sugarcane', 'Sweet potato', 'Tapioca',
       'Black pepper', 'Dry chillies', 'other oilseeds', 'Turmeric',
       'Maize', 'Moong(Green Gram)', 'Urad', 'Arhar/Tur', 'Groundnut',
       'Sunflower', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Horse-gram',
       'Jowar', 'Korra', 'Ragi', 'Tobacco', 'Gram', 'Wheat', 'Masoor',
       'Sesamum', 'Linseed', 'Safflower', 'Onion', 'other misc. pulses',
       'Samai', 'Small millets', 'Coriander', 'Potato',
       'Other  Rabi pulses', 'Soyabean', 'Beans & Mutter(Vegetable)',
       'Bhindi', 'Brinjal', 'Citrus Fruit', 'Cucumber', 'Grapes', 'Mango',
       'Orange', 'other fibres', 'Other Fresh Fruits', 'Other Vegetables',
       'Papaya', 'Pome Fruit', 'Tomato', 'Rapeseed &Mustard', 'Mesta',
       'Cowpea(Lobia)', 'Lemon', 'Pome Granet', 'Sapota', 'Cabbage',
       'Peas  (vegetable)', 'Niger seed', 'Bottle Gourd', 'Sannhamp',
       'Va

In [8]:
dataset["Crop"].value_counts()

Rice                 15104
Maize                13947
Moong(Green Gram)    10318
Urad                  9850
Sesamum               9046
                     ...  
Litchi                   6
Coffee                   6
Apple                    4
Peach                    4
Other Dry Fruit          1
Name: Crop, Length: 124, dtype: int64

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   State_Name     246091 non-null  object 
 1   District_Name  246091 non-null  object 
 2   Crop_Year      246091 non-null  int64  
 3   Season         246091 non-null  object 
 4   Crop           246091 non-null  object 
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB


In [37]:
from sklearn import preprocessing
lable_encoder = preprocessing.LabelEncoder()
dataset["State_Name"]= lable_encoder.fit_transform(dataset["State_Name"])
dataset["District_Name"]= lable_encoder.fit_transform(dataset["District_Name"])
dataset["Season"]= lable_encoder.fit_transform(dataset["Season"])
dataset["Crop"]= lable_encoder.fit_transform(dataset["Crop"])
dataset

State_Name  District_Name  Crop_Year  Season  Crop      Area  \
0                0            427       2000       1     2    1254.0   
1                0            427       2000       1    74       2.0   
2                0            427       2000       1    95     102.0   
3                0            427       2000       4     7     176.0   
4                0            427       2000       4    22     720.0   
...            ...            ...        ...     ...   ...       ...   
246086          32            471       2014       3    95     306.0   
246087          32            471       2014       3   102     627.0   
246088          32            471       2014       4   106     324.0   
246089          32            471       2014       5    95  279151.0   
246090          32            471       2014       5   102     175.0   

        Production  
0           2000.0  
1              1.0  
2            321.0  
3            641.0  
4            165.0  
...            ...  
246086       801.0  
246087       463.0  
246088     16250.0  
246089    597899.0  
246090        88.0  

[246091 rows x 7 columns]

In [38]:
dataset.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [48]:
a=dataset.dropna()
a

State_Name  District_Name  Crop_Year  Season  Crop      Area  \
0                0            427       2000       1     2    1254.0   
1                0            427       2000       1    74       2.0   
2                0            427       2000       1    95     102.0   
3                0            427       2000       4     7     176.0   
4                0            427       2000       4    22     720.0   
...            ...            ...        ...     ...   ...       ...   
246086          32            471       2014       3    95     306.0   
246087          32            471       2014       3   102     627.0   
246088          32            471       2014       4   106     324.0   
246089          32            471       2014       5    95  279151.0   
246090          32            471       2014       5   102     175.0   

        Production  
0           2000.0  
1              1.0  
2            321.0  
3            641.0  
4            165.0  
...            ...  
246086       801.0  
246087       463.0  
246088     16250.0  
246089    597899.0  
246090        88.0  

[242361 rows x 7 columns]

In [59]:
a=a.head(1000)
a

State_Name  District_Name  Crop_Year  Season  Crop     Area  Production
0              0            427       2000       1     2   1254.0      2000.0
1              0            427       2000       1    74      2.0         1.0
2              0            427       2000       1    95    102.0       321.0
3              0            427       2000       4     7    176.0       641.0
4              0            427       2000       4    22    720.0       165.0
...          ...            ...        ...     ...   ...      ...         ...
1001           1            122       1997       1    95  42300.0     84400.0
1002           1            122       1997       1    99   1300.0       200.0
1003           1            122       1997       1   102    400.0       100.0
1004           1            122       1997       1   106  29600.0   2775100.0
1005           1            122       1997       1   107   1300.0       600.0

[1000 rows x 7 columns]

In [60]:
a.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [61]:
x=a.iloc[:,:-1].values
y=a.iloc[:,-1].values
y

array([2.000000e+03, 1.000000e+00, 3.210000e+02, 6.410000e+02,
       1.650000e+02, 6.510000e+07, 1.000000e+02, 2.000000e+00,
       1.500000e+01, 1.690000e+02, 2.061000e+03, 1.000000e+00,
       3.000000e+02, 1.920000e+02, 6.443000e+07, 1.000000e+02,
       1.000000e+00, 3.300000e+01, 5.108400e+02, 2.083000e+03,
       1.278000e+03, 1.350000e+01, 2.080000e+02, 6.749000e+07,
       2.880000e+01, 1.330000e+02, 4.000000e+01, 9.017000e+01,
       1.525000e+03, 1.763000e+03, 1.586000e+01, 2.085000e+02,
       6.858000e+07, 1.020000e+02, 3.264000e+02, 3.000000e-01,
       7.257000e+01, 8.058500e+02, 4.041200e+02, 1.586000e+01,
       1.979000e+02, 5.238000e+07, 1.452000e+02, 3.660000e+02,
       1.100000e-01, 1.206000e+01, 5.820000e+02, 1.000000e-01,
       5.580000e+01, 5.203000e+07, 7.000000e+01, 4.776000e+02,
       9.760000e+02, 6.800000e-01, 8.513000e+01, 5.937000e+07,
       9.000000e+00, 2.100000e+01, 5.000000e-01, 8.600000e+01,
       4.500000e+02, 1.030000e+00, 1.000000e+01, 4.1750

In [62]:
x

array([[0.000e+00, 4.270e+02, 2.000e+03, 1.000e+00, 2.000e+00, 1.254e+03],
       [0.000e+00, 4.270e+02, 2.000e+03, 1.000e+00, 7.400e+01, 2.000e+00],
       [0.000e+00, 4.270e+02, 2.000e+03, 1.000e+00, 9.500e+01, 1.020e+02],
       ...,
       [1.000e+00, 1.220e+02, 1.997e+03, 1.000e+00, 1.020e+02, 4.000e+02],
       [1.000e+00, 1.220e+02, 1.997e+03, 1.000e+00, 1.060e+02, 2.960e+04],
       [1.000e+00, 1.220e+02, 1.997e+03, 1.000e+00, 1.070e+02, 1.300e+03]])

In [63]:
x.shape

(1000, 6)

In [64]:
y.shape

(1000,)

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=588)
x_train

array([[1.0000e+00, 2.4000e+01, 2.0050e+03, 1.0000e+00, 3.0000e+00,
        3.5013e+04],
       [1.0000e+00, 2.4000e+01, 2.0080e+03, 2.0000e+00, 1.1900e+02,
        1.6400e+02],
       [1.0000e+00, 2.4000e+01, 2.0090e+03, 1.0000e+00, 4.8000e+01,
        4.1409e+04],
       ...,
       [1.0000e+00, 2.4000e+01, 2.0110e+03, 1.0000e+00, 5.9000e+01,
        2.5447e+04],
       [1.0000e+00, 2.4000e+01, 2.0100e+03, 1.0000e+00, 9.0000e+01,
        1.8760e+03],
       [1.0000e+00, 2.4000e+01, 2.0110e+03, 1.0000e+00, 1.2300e+02,
        5.0000e+01]])

In [66]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [67]:
y_pred=regressor.predict(x_test)
y_pred

array([-2.32161599e+05,  4.06296964e+06,  2.04097654e+06, -2.47993417e+06,
        1.34546782e+06, -4.38434100e+05, -2.98243856e+05,  5.76117458e+04,
        5.04293363e+05,  5.22378283e+06,  1.87477354e+06,  2.02085460e+06,
       -4.48523078e+05,  2.12031516e+06,  5.33965394e+05,  1.20505702e+05,
       -6.28633409e+05, -4.80671766e+05,  2.20116023e+06,  9.49276732e+05,
        1.85579314e+05,  4.95557592e+06, -1.29283941e+06, -2.47336505e+05,
       -1.00632286e+06,  5.28072940e+06, -6.92124694e+04, -9.90874313e+05,
        4.21230159e+05,  4.05952858e+05,  2.68363438e+06,  1.62746290e+06,
       -3.49996374e+05,  6.52287401e+05, -5.81491208e+05,  4.89408693e+05,
        8.69648689e+05,  8.07450025e+04,  2.67352282e+05,  5.31487952e+05,
        4.93013774e+05, -7.07694783e+05,  2.71302247e+06, -1.30445102e+05,
        6.60945331e+05,  4.89852680e+06, -1.26697273e+04,  9.07632297e+05,
       -3.55710383e+05, -4.49704408e+04,  2.92991020e+06, -6.09111767e+05,
        2.81618554e+05, -

In [68]:
print("Train Accuracy:", regressor.score(x_train,y_train))
print("Test Accuracy:", regressor.score(x_test,y_pred))

Train Accuracy: 0.07720736994854815
Test Accuracy: 1.0
