# Importing lab..

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv(r"C:\Users\comp\Downloads\Employee (1).csv")
data

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB


# Delete unwanted coloumn

In [4]:
del (data["City"])

In [5]:
data

Education  JoiningYear  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017            3   34    Male          No   
1     Bachelors         2013            1   28  Female          No   
2     Bachelors         2014            3   38  Female          No   
3       Masters         2016            3   27    Male          No   
4       Masters         2017            3   24    Male         Yes   
...         ...          ...          ...  ...     ...         ...   
4648  Bachelors         2013            3   26  Female          No   
4649    Masters         2013            2   37    Male          No   
4650    Masters         2018            3   27    Male          No   
4651  Bachelors         2012            3   30    Male         Yes   
4652  Bachelors         2015            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 8 columns]

# Using label encoder for convert object to interger

In [6]:
from sklearn.preprocessing import LabelEncoder
A1=LabelEncoder()
data["Education"]=A1.fit_transform(data["Education"])
#data["City"]=A1.fit_transform(data["City"])
data["Gender"]=A1.fit_transform(data["Gender"])
data["EverBenched"]=A1.fit_transform(data["EverBenched"])

In [7]:
data

Education  JoiningYear  PaymentTier  Age  Gender  EverBenched  \
0             0         2017            3   34       1            0   
1             0         2013            1   28       0            0   
2             0         2014            3   38       0            0   
3             1         2016            3   27       1            0   
4             1         2017            3   24       1            1   
...         ...          ...          ...  ...     ...          ...   
4648          0         2013            3   26       0            0   
4649          1         2013            2   37       1            0   
4650          1         2018            3   27       1            0   
4651          0         2012            3   30       1            1   
4652          0         2015            3   33       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 8 columns]

In [8]:
data["LeaveOrNot"].value_counts()

0    3053
1    1600
Name: LeaveOrNot, dtype: int64

# Data slicing

In [9]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
y

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

# Data imbalancing using SMOTE

In [10]:
from imblearn.over_sampling import SMOTE
S= SMOTE()
x_data,y_data=S.fit_resample(x,y)


In [11]:
from collections import Counter

In [12]:
Counter(y_data)

Counter({0: 3053, 1: 3053})

# Split the data

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=11)

# Cross Validation LogisticRegression

In [14]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=11,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=5, random_state=11, shuffle=True)


In [15]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
L=LogisticRegression()

In [16]:
scores=cross_val_score(L,x_train,y_train,cv=kf)
y_pred=cross_val_predict(L,x_test,y_test,cv=kf)
print(Counter(y_train))
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print(Counter(y_test))
print('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
print(scores)
print('////////////////////////////////////////////////')
print(y_pred)
print('><><><><><><><><><><><><><><><><><><><><><><><><')
print(np.mean(scores)*100)

Counter({0: 2474, 1: 2410})
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Counter({1: 643, 0: 579})
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[0.63664278 0.64073695 0.64278403 0.63357216 0.63831967]
////////////////////////////////////////////////
[0 0 1 ... 1 0 1]
><><><><><><><><><><><><><><><><><><><><><><><><
63.841111968723254


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100


65.38461538461539

# Ensemble Techniques

In [18]:
L.fit(x_train,y_train)

LogisticRegression()

In [19]:
y_pred1=L.predict(x_test)
y_pred1

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred1,y_test)*100


65.30278232405891

# KNeighborsClassifier

In [21]:
from sklearn.neighbors import KNeighborsClassifier
I=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=1)
I.fit(x_train,y_train)

KNeighborsClassifier(p=1)

In [22]:
y_pred2=I.predict(x_test)
y_pred2

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)*100

76.02291325695582

# StratifiedKFold

In [24]:
from sklearn.model_selection import StratifiedKFold
sf=StratifiedKFold(n_splits=5,random_state=10,shuffle=True)
sf.get_n_splits(x_data,y_data)
for train_data,test_data in sf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(L,x_train,y_train,cv=kf)
    y_pred1=cross_val_predict(L,x_test,y_test,cv=kf)
    print(Counter(y_test))
    print(scores)
    print('//////////////////////////')
    print(y_pred1)
    print('><><><><><><><><><><><><><><><>')
    print(np.mean(scores)*100)
    print('#############################')
    print(x_test,y_test)
    print('><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>')

C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Counter({1: 611, 0: 611})
[0.64994882 0.59877175 0.65097236 0.60593654 0.68032787]
//////////////////////////
[1 0 1 ... 1 1 1]
><><><><><><><><><><><><><><><>
63.71914693692635
#############################
[[   0 2013    1 ...    0    0    3]
 [   0 2016    3 ...    1    0    0]
 [   0 2016    3 ...    0    0    2]
 ...
 [   0 2015    3 ...    0    0    0]
 [   0 2017    2 ...    0    0    4]
 [   0 2017    2 ...    0    0    1]] [1 0 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({0: 611, 1: 610})
[0.61924258 0.64994882 0.64380757 0.62640737 0.6468782 ]
//////////////////////////
[0 0 1 ... 1 0 0]
><><><><><><><><><><><><><><><>
63.725690890481054
#############################
[[   1 2017    3 ...    1    1    2]
 [   1 2017    2 ...    1    0    2]
 [   1 2017    2 ...    0    0    2]
 ...
 [   0 2017    2 ...    0    0    5]
 [   0 2016    3 ...    1    0    1]
 [   0 2016    3 ...    1    1    3]] [1 0 0 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>
Counter({0: 611, 1: 610})
[0.62845445 0.67246673 0.60798362 0.62436029 0.64278403]
//////////////////////////
[1 1 1 ... 1 0 1]
><><><><><><><><><><><><><><><>
63.52098259979528
#############################
[[   0 2017    1 ...    1    0    3]
 [   0 2015    2 ...    0    0    0]
 [   0 2016    2 ...    0    0    0]
 ...
 [   0 2012    3 ...    0    0    3]
 [   1 2017    2 ...    1    0    5]
 [   0 2017    2 ...    0    0    4]

# RandomForestClassifier

In [25]:
from sklearn.ensemble import RandomForestClassifier
R1=RandomForestClassifier()
R1.fit(x_train,y_train)

RandomForestClassifier()

In [26]:
y_pred3=R1.predict(x_test)
y_pred3

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
aa3=accuracy_score(y_pred3,y_test)*100
aa3

79.03357903357903

# Conclusion

By using the different algorithum we get different accuracy_score. Best accuracy_score 80.18 by using Random Forest Classifier

# Using feature constrution convert the Age into category like 0 and 1

In [28]:
data

Education  JoiningYear  PaymentTier  Age  Gender  EverBenched  \
0             0         2017            3   34       1            0   
1             0         2013            1   28       0            0   
2             0         2014            3   38       0            0   
3             1         2016            3   27       1            0   
4             1         2017            3   24       1            1   
...         ...          ...          ...  ...     ...          ...   
4648          0         2013            3   26       0            0   
4649          1         2013            2   37       1            0   
4650          1         2018            3   27       1            0   
4651          0         2012            3   30       1            1   
4652          0         2015            3   33       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 8 columns]

In [29]:
data.describe()

Education  JoiningYear  PaymentTier          Age       Gender  \
count  4653.00000  4653.000000  4653.000000  4653.000000  4653.000000   
mean      0.26456  2015.062970     2.698259    29.393295     0.597034   
std       0.52112     1.863377     0.561435     4.826087     0.490547   
min       0.00000  2012.000000     1.000000    22.000000     0.000000   
25%       0.00000  2013.000000     3.000000    26.000000     0.000000   
50%       0.00000  2015.000000     3.000000    28.000000     1.000000   
75%       0.00000  2017.000000     3.000000    32.000000     1.000000   
max       2.00000  2018.000000     3.000000    41.000000     1.000000   

       EverBenched  ExperienceInCurrentDomain   LeaveOrNot  
count  4653.000000                4653.000000  4653.000000  
mean      0.102729                   2.905652     0.343864  
std       0.303638                   1.558240     0.475047  
min       0.000000                   0.000000     0.000000  
25%       0.000000                   2.000000     0.000000  
50%       0.000000                   3.000000     0.000000  
75%       0.000000                   4.000000     1.000000  
max       1.000000                   7.000000     1.000000

# Using For loop

In [30]:
NEW_AGE=[]
for x in data["Age"]:
    if x>=22 and x<=30:
        NEW_AGE.append(0)
    else:
        NEW_AGE.append(1)
print(NEW_AGE)        
        
        
    

[1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [31]:
data.insert(3,"NEW_AGE",NEW_AGE)
data

Education  JoiningYear  PaymentTier  NEW_AGE  Age  Gender  EverBenched  \
0             0         2017            3        1   34       1            0   
1             0         2013            1        0   28       0            0   
2             0         2014            3        1   38       0            0   
3             1         2016            3        0   27       1            0   
4             1         2017            3        0   24       1            1   
...         ...          ...          ...      ...  ...     ...          ...   
4648          0         2013            3        0   26       0            0   
4649          1         2013            2        1   37       1            0   
4650          1         2018            3        0   27       1            0   
4651          0         2012            3        0   30       1            1   
4652          0         2015            3        1   33       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [32]:
del(data["Age"])
data

Education  JoiningYear  PaymentTier  NEW_AGE  Gender  EverBenched  \
0             0         2017            3        1       1            0   
1             0         2013            1        0       0            0   
2             0         2014            3        1       0            0   
3             1         2016            3        0       1            0   
4             1         2017            3        0       1            1   
...         ...          ...          ...      ...     ...          ...   
4648          0         2013            3        0       0            0   
4649          1         2013            2        1       1            0   
4650          1         2018            3        0       1            0   
4651          0         2012            3        0       1            1   
4652          0         2015            3        1       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 8 columns]

In [33]:
del(data["JoiningYear"])
data

Education  PaymentTier  NEW_AGE  Gender  EverBenched  \
0             0            3        1       1            0   
1             0            1        0       0            0   
2             0            3        1       0            0   
3             1            3        0       1            0   
4             1            3        0       1            1   
...         ...          ...      ...     ...          ...   
4648          0            3        0       0            0   
4649          1            2        1       1            0   
4650          1            3        0       1            0   
4651          0            3        0       1            1   
4652          0            3        1       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 7 columns]

In [34]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,-1].values


In [35]:
from imblearn.over_sampling import SMOTE
S= SMOTE()
X_data,Y_data=S.fit_resample(X,Y)


In [36]:
from sklearn.model_selection import KFold
kf1=KFold(n_splits=5,random_state=11,shuffle=True)
kf1.get_n_splits(X_data)
print(kf1)

KFold(n_splits=5, random_state=11, shuffle=True)


In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y_data,test_size=0.2,random_state=11)

In [38]:
score=cross_val_score(L,X_train,Y_train,cv=kf1)
y_pred11=cross_val_predict(L,X_test,Y_test,cv=kf1)
print(Counter(Y_train))
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print(Counter(Y_test))
print('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
print(score)
print('////////////////////////////////////////////////')
print( y_pred11)
print('><><><><><><><><><><><><><><><><><><><><><><><><')
print(np.mean(score)*100)

Counter({0: 2474, 1: 2410})
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Counter({1: 643, 0: 579})
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[0.62538383 0.6223132  0.63971341 0.61924258 0.62602459]
////////////////////////////////////////////////
[0 1 1 ... 1 0 1]
><><><><><><><><><><><><><><><><><><><><><><><><
62.65355219222444


# Conclusion

By converting the data in category form using the for loop the accuracy_score is 62.77