In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"C:\Users\comp\Downloads\brain_stroke.csv")
data

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [4]:
data['stroke'].value_counts()

0    4733
1     248
Name: stroke, dtype: int64

# Label Encoder

In [5]:
from sklearn.preprocessing import LabelEncoder
L=LabelEncoder()
data["ever_married"]=L.fit_transform(data["ever_married"])
data["work_type"]=L.fit_transform(data["work_type"])
data["Residence_type"]=L.fit_transform(data["Residence_type"])
data["smoking_status"]=L.fit_transform(data["smoking_status"])
data                    
                    
                    
                    

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       Male  67.0             0              1             1          1   
1       Male  80.0             0              1             1          1   
2     Female  49.0             0              0             1          1   
3     Female  79.0             1              0             1          2   
4       Male  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976    Male  41.0             0              0             0          1   
4977    Male  40.0             0              0             1          1   
4978  Female  45.0             1              0             1          0   
4979    Male  40.0             0              0             1          1   
4980  Female  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  1             228.69  36.6               1       1  
1                  0             105.92  32.5               2       1  
2                  1             171.23  34.4               3       1  
3                  0             174.12  24.0               2       1  
4                  1             186.21  29.0               1       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               1       0  
4977               1             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               1              83.75  29.1               2       0  

[4981 rows x 11 columns]

In [6]:
x=data.iloc[:,2:-1].values
y=data.iloc[:,-1].values
print(x)
print(y)

[[  0.     1.     1.   ... 228.69  36.6    1.  ]
 [  0.     1.     1.   ... 105.92  32.5    2.  ]
 [  0.     0.     1.   ... 171.23  34.4    3.  ]
 ...
 [  1.     0.     1.   ...  95.02  31.8    3.  ]
 [  0.     0.     1.   ...  83.94  30.     3.  ]
 [  1.     0.     1.   ...  83.75  29.1    2.  ]]
[1 1 1 ... 0 0 0]


# Data imbalalncing

In [7]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x_data,y_data=s.fit_resample(x,y)

In [8]:
from collections import Counter
Counter(y_data)

Counter({1: 4733, 0: 4733})

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)
Counter(y_test)

Counter({0: 944, 1: 950})

# Random Forest Classifier

In [10]:
from sklearn.ensemble import RandomForestClassifier
R=RandomForestClassifier()
R.fit(x_train,y_train)

RandomForestClassifier()

In [11]:
y_pred=R.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Accuacy Score and Confusion matrix

In [12]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_pred,y_test)*100
a

97.20168954593453

In [13]:
from sklearn.metrics import confusion_matrix
a1=confusion_matrix(y_pred,y_test)*100
a1

array([[93700,  4600],
       [  700, 90400]], dtype=int64)

# Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier(criterion='entropy',random_state=0)
DT.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [15]:
y_pred1=DT.predict(x_test)
y_pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
a1=accuracy_score(y_pred1,y_test)*100
a1

95.08975712777192

In [17]:
from sklearn.metrics import confusion_matrix
CF2=confusion_matrix(y_test,y_pred1)*100
CF2



array([[90300,  4100],
       [ 5200, 89800]], dtype=int64)

# Cross Validation

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
L=LogisticRegression()


In [19]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=11,shuffle=True)
kf.get_n_splits(x_data)
print(kf)

KFold(n_splits=5, random_state=11, shuffle=True)


In [20]:
from sklearn.model_selection import StratifiedKFold
sf=StratifiedKFold(n_splits=5,random_state=10,shuffle=True)     # n_splits means the no of the sapmle
sf.get_n_splits(x_data,y_data)                                     # here we use the balance data direct
for train_data,test_data in sf.split(x_data,y_data):          # using for loop
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(L,x_train,y_train,cv=kf)
    y_pred1=cross_val_predict(L,x_test,y_test,cv=kf)
    print(Counter(y_test))
    print(scores)
    print('//////////////////////////')
    print(y_pred1)
    print('><><><><><><><><><><><><><><><>')
    print(np.mean(scores)*100)
    print('#############################')
    print(x_test,y_test)
    print('><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>')

C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({1: 947, 0: 947})
[0.68118812 0.70891089 0.68758256 0.69220608 0.69682959]
//////////////////////////
[0 0 1 ... 0 1 0]
><><><><><><><><><><><><><><><>
69.3343447951136
#############################
[[  0.           0.           0.         ...  94.39        22.8
    2.        ]
 [  0.           0.           0.         ...  89.22        37.8
    2.        ]
 [  0.           0.           1.         ... 228.7         26.6
    2.        ]
 ...
 [  0.           0.           0.22924175 ...  94.08281606  23.12093845
    2.        ]
 [  0.           0.26112879   1.         ... 228.14741652  28.02670909
    2.        ]
 [  0.           0.           1.         ...  82.3220784   30.10475986
    2.95670903]] [1 1 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({1: 947, 0: 946})
[0.68448845 0.68712871 0.70759076 0.69550859 0.70409511]
//////////////////////////
[1 0 1 ... 0 0 1]
><><><><><><><><><><><><><><><>
69.57623239206352
#############################
[[  0.           1.           1.         ... 105.92        32.5
    2.        ]
 [  0.           0.           1.         ... 171.23        34.4
    3.        ]
 [  0.           1.           1.         ... 191.61        37.5
    3.        ]
 ...
 [  0.51691237   0.           0.48308763 ...  79.01222892  30.23139639
    2.        ]
 [  0.           0.           1.         ...  77.63952832  24.01552417
    1.        ]
 [  0.69595637   0.           1.         ...  90.7098755   32.62636073
    1.30404363]] [1 1 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({1: 947, 0: 946})
[0.70561056 0.70363036 0.70759076 0.69749009 0.70805812]
//////////////////////////
[1 1 1 ... 0 0 1]
><><><><><><><><><><><><><><><>
70.44759799625933
#############################
[[  1.           0.           1.         ... 174.12        24.
    2.        ]
 [  0.           1.           1.         ... 214.09        28.2
    2.        ]
 [  1.           0.           1.         ... 167.41        30.9
    2.        ]
 ...
 [  0.55811772   0.           0.44188228 ...  80.89912453  29.92094114
    2.44188228]
 [  0.           0.           1.         ...  69.73709814  29.78875063
    0.52812342]
 [  0.69954305   0.           1.         ... 199.64770755  27.57936027
    0.69954305]] [1 1 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({0: 947, 1: 946})
[0.7049505  0.68712871 0.70825083 0.70343461 0.70607662]
//////////////////////////
[0 1 0 ... 1 0 1]
><><><><><><><><><><><><><><><>
70.19682523073972
#############################
[[0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 5.85700000e+01
  2.42000000e+01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 1.93940000e+02
  2.24000000e+01 3.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 1.04120000e+02
  2.35000000e+01 2.00000000e+00]
 ...
 [0.00000000e+00 1.59681306e-02 1.00000000e+00 ... 2.35709202e+02
  3.22856287e+01 2.01596813e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 5.99228526e+01
  2.80056118e+01 1.05611841e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 ... 2.64382151e+02
  3.00413167e+01 3.00000000e+00]] [1 1 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

Counter({0: 947, 1: 946})
[0.70429043 0.69306931 0.70231023 0.68824306 0.71136063]
//////////////////////////
[1 1 1 ... 0 1 0]
><><><><><><><><><><><><><><><>
69.9854733161559
#############################
[[  0.           1.           1.         ... 228.69        36.6
    1.        ]
 [  0.           0.           1.         ... 186.21        29.
    1.        ]
 [  1.           1.           1.         ...  70.09        27.4
    2.        ]
 ...
 [  0.           0.           1.         ...  96.91771691  27.29631974
    2.28009992]
 [  0.27378248   0.           1.         ...  78.8328539   28.86194803
    1.        ]
 [  0.           0.           1.         ... 135.84838583  28.83915455
    1.        ]] [1 1 1 ... 1 1 1]
><><><><><><><><><><><><><><><><><><<>><><><><><><><><><><><><><><><><<><><><><><><><><><>>><><><><><><>>><><>


C:\Users\comp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
AAA=StandardScaler()
Q=AAA.fit_transform(x_data)
Q

array([[-0.51975778,  3.14359265,  0.56999117, ...,  2.02916951,
         1.22598175, -0.44762617],
       [-0.51975778,  3.14359265,  0.56999117, ..., -0.21639463,
         0.54993163,  0.59325425],
       [-0.51975778, -0.4046449 ,  0.56999117, ...,  0.97817891,
         0.86322315,  1.63413467],
       ...,
       [-0.51975778, -0.4046449 ,  0.56999117, ..., -0.73366769,
        -0.8490759 , -0.44762617],
       [-0.51975778, -0.4046449 ,  0.56999117, ...,  0.33102013,
        -0.05370617, -0.44762617],
       [ 1.53340748, -0.4046449 ,  0.56999117, ..., -0.4946003 ,
         0.57076729, -0.13115311]])

In [22]:
AAA

StandardScaler()

In [35]:
Q.min()

-2.50053841491534

In [24]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(Q,y_data,test_size=0.2,random_state=0)
Counter(y_test)

Counter({1: 946, 0: 947})

# Random Forest Classifier

In [25]:
from sklearn.ensemble import RandomForestClassifier
R1=RandomForestClassifier()
R1.fit(x_train1,y_train1)

RandomForestClassifier()

In [26]:
y_pred11=R1.predict(x_test1)
y_pred11

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
W=accuracy_score(y_pred11,y_test1)*100
W

97.14889123548046

# Decision Tree Classifier

In [28]:
from sklearn.tree import DecisionTreeClassifier
DTT=DecisionTreeClassifier(criterion='entropy',random_state=0)
DTT.fit(x_train1,y_train1)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [29]:
y_predq=DTT.predict(x_test1)
y_predq

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_predq,y_test1)*100

95.08975712777192